###############################
## training settings
#---------------------
max_iter: 30000
batch_size: 8
val_batch_size: 4
test_batch_size: 8
num_instance: 0


###############################
## print settings
#---------------------
log_iter: 200
image_save_iter: 5000
snapshot_save_iter: 10000


###############################
## optimizer
#-----------------
scheduler:
  lr_policy: multistep
  step_size: 20000
